- name: Ensure required base packages are installed
  apt:
    name:
      - gnupg
      - curl
      - ca-certificates
      - lsb-release
      - software-properties-common
    state: present
    update_cache: yes

- name: Remove existing MongoDB repository file (if any)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/mongodb-org-7.0.list
    state: absent

- name: Add MongoDB APT key
  ansible.builtin.apt_key:
    url: https://pgp.mongodb.com/server-7.0.asc
    state: present

- name: Add MongoDB repository for Debian 12
  ansible.builtin.apt_repository:
    repo: 'deb [ arch=amd64 ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main'
    state: present
    filename: mongodb-org-7.0

- name: Install MongoDB
  apt:
    name:
      - mongodb-org
    state: present
    update_cache: yes

- name: Enable and start MongoDB
  service:
    name: mongod
    state: started
    enabled: yes
