- name: Ensure required base packages are installed
  apt:
    name:
      - gnupg
      - curl
      - ca-certificates
      - lsb-release
      - software-properties-common
    state: present
    update_cache: yes

- name: Remove old MongoDB repo file if it exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/mongodb-org-7.0.list
    state: absent

- name: Download MongoDB GPG key
  ansible.builtin.get_url:
    url: https://pgp.mongodb.com/server-7.0.asc
    dest: /usr/share/keyrings/mongodb-server-7.0.gpg
    mode: '0644'

- name: Add MongoDB repository for Debian 12
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main"
    state: present
    filename: mongodb-org-7.0

- name: Install MongoDB
  apt:
    name:
      - mongodb-org
    state: present
    update_cache: yes

- name: Enable and start MongoDB
  service:
    name: mongod
    state: started
    enabled: yes
